# .github/workflows/reddit_bot.yml
name: Reddit Bot Automation

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  issues:
    types: [opened]  # Triggered when an issue is opened

jobs:
  run-reddit-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Environment Variables
        run: |
          echo "CLIENT_ID: $CLIENT_ID"
          echo "CLIENT_SECRET: $CLIENT_SECRET"
          echo "USERNAME: $USERNAME"
          echo "USER_AGENT: $USER_AGENT"

      - name: Run Reddit Bot
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USERNAME: ${{ secrets.REDDIT_USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER_AGENT: 'your_bot_user_agent'
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            python reddit_bot.py --manual "$(jq -r '.issue.body' < $GITHUB_EVENT_PATH)"
          else
            python reddit_bot.py
          fi
