# .github/workflows/manual_reddit_response.yml
name: Reddit Bot Manual Trigger

on:
  issues:
    types: [opened]

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot for Manual Post
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USERNAME: ${{ secrets.REDDIT_USERNAME }}
          PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          USER_AGENT: 'your_bot_user_agent'
        run: |
          python reddit_bot.py --manual "$(jq -r '.issue.body' < $GITHUB_EVENT_PATH)"
