name: Run Script

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Full botrun command in the format !botrun(script-name-arguments)'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency installation."
          fi

      - name: Parse script name and arguments from command
        run: |
          # Extract script name and arguments from the input command
          COMMAND="${{ github.event.inputs.command }}"
          if [[ $COMMAND =~ !botrun\(([^-]+)-?(.*)\) ]]; then
            SCRIPT_NAME="${BASH_REMATCH[1]}"
            ARGUMENTS="${BASH_REMATCH[2]}"
          else
            echo "Invalid command format. Expected: !botrun(script-name-arguments)"
            exit 1
          fi
          echo "Script name: $SCRIPT_NAME"
          echo "Arguments: $ARGUMENTS"

      - name: Run the specified script
        run: |
          echo "Running script: $SCRIPT_NAME with arguments: $ARGUMENTS"
          python scripts/$SCRIPT_NAME $ARGUMENTS > output.log 2>&1 || echo "Script failed. Check output.log for details."

      - name: Upload output log
        uses: actions/upload-artifact@v3
        with:
          name: script-output
          path: output.log

      - name: Notify on script failure
        if: failure()
        run: echo "Script execution failed. Please check the 'script-output' artifact for details."
