name: Reddit Bot Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # Check for new posts every 30 minutes
    - cron: '0 * * * *'     # Run the full system every hour
  issues:
    types: [opened]         # Triggered when an issue is opened

jobs:
  install-ollama:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v2

      # Cache Python packages
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Ollama
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      # Verify Ollama installation
      - name: Verify Ollama Installation
        run: |
          ollama --version

      # Start Ollama Service
      - name: Start Ollama Service
        run: |
          nohup ollama serve &

  process-issue:
    runs-on: ubuntu-latest
    needs: install-ollama

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Issue Info and Run Reddit Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=$(jq --raw-output .issue.number $GITHUB_EVENT_PATH)
          python reddit_bot.py $ISSUE_NUMBER
